name: CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install and check code format
        run: |
          yarn install
          yarn format:check

      - name: Run unit test
        run: yarn test -- --coverage
        env:
          CI: true

      - name: Build and deploy
        if: github.event_name == 'push'
        run: |
          yarn build
          npx surge --project ./build --domain short-rice.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
